### ISSUE TITLE
Are there any documents?

### ISSUE THREAD

**Issue by GabrielLin** [pshah123/neural-rewriter#1]
Thanks.

**Comment by RomaniukVadim** [comment]
Forked and add doc. https://github.com/RomaniukVadim/neural-rewriter

**Comment by cuuupid** [comment]
Thanks! This project is very largely based off of [ryankiros's neural storyteller repo](https://github.com/ryankiros/neural-storyteller) so the documentation there should also be somewhat useful.

Closing this as PR #2 fixes this (thank you @RomaniukVadim!)
